---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homeassistant-proxy-config
  labels:
    app.kubernetes.io/name: homeassistant
    app.kubernetes.io/instance: homeassistant
data:
  proxy.yaml: |
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.42.0.0/16
