---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-config
  labels:
    app.kubernetes.io/name: homeassistant
    app.kubernetes.io/instance: homeassistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
