---
# Source: household-planner/templates/externalsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: planner-secrets
  labels:
    app.kubernetes.io/name: household-planner
    app.kubernetes.io/instance: planner
    app.kubernetes.io/version: "0.3.1"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: household-planner-0.3.1
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-store
    kind: ClusterSecretStore
  target:
    name: planner-secrets
    creationPolicy: Owner
  data:
    - secretKey: auth-secret
      remoteRef:
        key: household-planner/auth-secret
    - secretKey: google-client-id
      remoteRef:
        key: household-planner/google-client-id
    - secretKey: google-client-secret
      remoteRef:
        key: household-planner/google-client-secret
    - secretKey: postgres-password
      remoteRef:
        key: household-planner/postgres-password

