---
# Source: household-planner/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: planner
  labels:
    app.kubernetes.io/name: household-planner
    app.kubernetes.io/instance: planner
    app.kubernetes.io/version: "0.3.1"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: household-planner-0.3.1
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: household-planner
    app.kubernetes.io/instance: planner
  ports:
    - name: http
      port: 80
      targetPort: http

