---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-secrets
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: minio
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-store
    kind: ClusterSecretStore
  target:
    name: minio-secrets
    creationPolicy: Owner
  data:
    - secretKey: root-user
      remoteRef:
        key: minio
        property: root-user
    - secretKey: root-password
      remoteRef:
        key: minio
        property: root-password
