---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: minio
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  volumeName: pvc-97bc58a1-8269-4627-8fe5-fea501bebdaa
  resources:
    requests:
      storage: 500Gi
