---
# Source: web/templates/externalsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: web-secrets
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/instance: web
    app.kubernetes.io/managed-by: Helm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-store
    kind: ClusterSecretStore
  target:
    name: web-secrets
    creationPolicy: Owner
  data:
    - secretKey: auth-secret
      remoteRef:
        key: web/AUTH_SECRET
    - secretKey: google-client-id
      remoteRef:
        key: web/AUTH_GOOGLE_ID
    - secretKey: google-client-secret
      remoteRef:
        key: web/AUTH_GOOGLE_SECRET
    - secretKey: postgres-password
      remoteRef:
        key: web/PGPASSWORD

