---
# Source: web/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-images
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/instance: web
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi

